---
title: "POO, documentation et tests"
description: "Programme du cours"
author: "Ludovic Deneuville"
format: 
  html:
    toc: true
    toc-location: left
    toc-expand: 3
from: markdown+emoji
number-sections: true
number-depth: 3
---

::: {.callout-important}
Les cours et les sujets des TP sont disponibles sur Moodle.

Le contenu de ce site vient en complément (pour vous aider) mais ne se substitue en aucun cas aux supports donnés par votre professeur.
:::

## Cours

Le programme est le suivant :

- Documentation du code
- Exceptions
- Tests unitaires avec *pytest*
- Découverte du paradigme objet
- Modélisation UML

## TP

6 TP et 1 TD de 3h chacun :

- [TP1](tp1.qmd) : Programmation Python et Visual Studio Code
- [TP2](tp2.qmd) : Modules, style de code, exceptions et tests
- [TP3](tp3.qmd) : Structures hétérogènes de données et tests
- [TP4](tp4.qmd) : Classes, objets, attributs et méthodes en Python
- [TP5](tp5.qmd) : Classes et diagrammes UML
- [TP6](tp6.qmd) : Relations entre classes
- [TD7](td7.qmd) : Héritages, relations, UML, modélisation



Vous pouvez réaliser les TP, soit :

- sur l'un des Datalab
  - du [GENES](https://onyxia.lab.groupe-genes.fr/) :arrow_right: [Lancer le service VScode-python](https://onyxia.lab.groupe-genes.fr/launcher/ide/vscode-python?name=vscode-python&version=2.1.23&s3=region-96a5c8b9&resources.limits.cpu=%C2%AB20000m%C2%BB){target="_blank"}
  - le [SSP Cloud](https://datalab.sspcloud.fr/){target="_blank"} de l'INSEE :arrow_right: [Lancer le service VScode-python](https://datalab.sspcloud.fr/launcher/ide/vscode-python?name=vscode-python&version=2.1.23&s3=region-ec97c721&resources.limits.cpu=%C2%AB20000m%C2%BB&autoLaunch=true){target="_blank"}
- sur votre VM ENSAI (depuis les postes clients légers des salles info ou en vous connectant à votre VM après avoir installé VMWare)
- sur votre machine personnelle, en installant python et VScode (voir mail de votre professeur)
