var:
  url-repo: https://github.com/ludo2ne/ENSAI-1A-Python   # to call this value : {{< meta var.url-repo >}}

project:
  type: website

website:
  title: "Python 1A"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#447099"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - text: Remise en jambe
        menu:
          - href: remise-en-jambe/tp1.qmd
            text: "TP n°1"
      - text: TP POO
        menu:
          - href: poo-tp/tp1.qmd
            text: "TP n°1"
          - href: poo-tp/tp2.qmd
            text: "TP n°2"
          - href: poo-tp/tp3.qmd
            text: "TP n°3"
          - href: poo-tp/tp4.qmd
            text: "TP n°4"
          - href: poo-tp/tp5.qmd
            text: "TP n°5"
          - href: poo-tp/tp6.qmd
            text: "TP n°6"
          - href: poo-tp/td7.qmd
            text: "TD n°7"
    right:
      - href: ressources.qmd
        text: Ressources    
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Source code]({{< meta var.url-repo >}}){.external target="_blank"}

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
