var:
  url-repo: https://github.com/ludo2ne/ENSAI-1A-Python   # to call this value : {{< meta var.url-repo >}}

project:
  type: website

website:
  title: "Python 1A"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#447099"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - text: Remise en jambe
        menu:
          - href: remise-en-jambe/intro.qmd
            text: "Introduction"
          - href: remise-en-jambe/tp1.qmd
            text: "TP n°1"
          - href: remise-en-jambe/tp2/2023/tp2-2023-2024.qmd
            text: "TP n°2 2023-2024"
          - href: remise-en-jambe/tp2/2024/tp2-2024-2025.qmd
            text: "TP n°2 2024-2025"
      - text: TP POO
        menu:
          - href: poo-tp/intro.qmd
            text: "Introduction"
          - href: poo-tp/tp1.qmd
            text: "TP n°1"
          - href: poo-tp/tp2.qmd
            text: "TP n°2"
          - href: poo-tp/tp3.qmd
            text: "TP n°3"
          - href: poo-tp/tp4.qmd
            text: "TP n°4"
          - href: poo-tp/tp5.qmd
            text: "TP n°5"
          - href: poo-tp/tp6.qmd
            text: "TP n°6"
          - href: poo-tp/td7.qmd
            text: "TD n°7"
    right:
      - text: Cours
        menu:
          - href: cours/print.qmd
            text: "La fonction Print"
          - href: cours/liste-dico.qmd
            text: "Listes et Dictionnaires"
          - href: cours/fonctions.qmd
            text: "Les Fonctions"
          - href: cours/exceptions.qmd
            text: "Les Exceptions"
          - href: cours/tu.qmd
            text: "Les Tests Unitaires"
      - href: exercices.qmd
        text: Exercices
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Source code]({{< meta var.url-repo >}}){.external target="_blank"}

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
